# .readthedocs.yaml

version: 2

# Set the build system
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Python configuration
python:
  install:
    - requirements: requirements.txt

# Sphinx configuration
sphinx:
  configuration: conf.py  # Adjust path if your conf.py is elsewhere
